### PR TITLE
Fix switchlevels calling deflateParams() with a stale buffer

### LINKED ISSUE #776: GH-536-incomplete-read segfault on SystemZ
Hi!

This new test segfaults for me as follows:

```
$ gdb -ex 'set args 6 88933 1 195840 2 45761 <test/data/lcet10.txt' ./switchlevels

...

__memcpy_z196 () at ../sysdeps/s390/memcpy-z900.S:191
191	../sysdeps/s390/memcpy-z900.S: No such file or directory.
(gdb) bt
#0  __memcpy_z196 () at ../sysdeps/s390/memcpy-z900.S:191
#1  0x7dfbd9e8 in flush_pending (strm=strm@entry=0x7ffff290) at /home/iii/zlib-ng/arch-systemz/gcc/m31/dfltcc-deflate/deflate.c:746
#2  0x7dfbf59c in deflate (flush=3, strm=0x7ffff290) at /home/iii/zlib-ng/arch-systemz/gcc/m31/dfltcc-deflate/deflate.c:1025
#3  deflate (strm=0x7ffff290, flush=3) at /home/iii/zlib-ng/arch-systemz/gcc/m31/dfltcc-deflate/deflate.c:766
#4  0x7dfbfbee in deflateParams (strm=strm@entry=0x7ffff290, level=level@entry=1, strategy=strategy@entry=0) at /home/iii/zlib-ng/arch-systemz/gcc/m31/dfltcc-deflate/deflate.c:613
#5  0x00400a0a in compress_chunk (last=<optimized out>, size=195840, level=1, strm=0x7ffff290) at /home/iii/zlib-ng/arch-systemz/gcc/m31/dfltcc-deflate/test/switchlevels.c:69
#6  main (argc=7, argv=<optimized out>) at /home/iii/zlib-ng/arch-systemz/gcc/m31/dfltcc-deflate/test/switchlevels.c:155
```

64-bit build with ASAN:

```
=================================================================
==1731846==ERROR: AddressSanitizer: heap-use-after-free on address 0x61700000009a at pc 0x0000010bdf04 bp 0x03ffffffeb10 sp 0x03ffffffe2f8
WRITE of size 5 at 0x61700000009a thread T0
[Detaching after fork from child process 1731849]
    #0 0x10bdf03 in __asan_memcpy /home/iii/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:22:3
    #1 0x3fffdf1d8e9 in flush_pending /home/iii/zlib-ng/arch-systemz/clang/asan-on/libfuzzer-off/dfltcc-deflate/deflate.c:746:5
    #2 0x3fffdf1d8e9 in deflate /home/iii/zlib-ng/arch-systemz/clang/asan-on/libfuzzer-off/dfltcc-deflate/deflate.c:1025:13
    #3 0x3fffdf1815f in deflateParams /home/iii/zlib-ng/arch-systemz/clang/asan-on/libfuzzer-off/dfltcc-deflate/deflate.c:613:19
    #4 0x10f5ae7 in compress_chunk /home/iii/zlib-ng/arch-systemz/clang/asan-on/libfuzzer-off/dfltcc-deflate/test/switchlevels.c:69:11
    #5 0x10f5ae7 in main /home/iii/zlib-ng/arch-systemz/clang/asan-on/libfuzzer-off/dfltcc-deflate/test/switchlevels.c:155:13
    #6 0x3fffd9ab5f9 in __libc_start_main /media/scsi/rpmbuild/BUILD/glibc-2.30-34-g994e529a37/csu/libc-start.c:308:16
    #7 0x1021155 in _start (/home/iii/zlib-ng/arch-systemz/clang/asan-on/libfuzzer-off/dfltcc-deflate/switchlevels+0x1021155)

0x61700000009a is located 26 bytes inside of 737-byte region [0x617000000080,0x617000000361)
freed by thread T0 here:
    #0 0x10bece3 in free /home/iii/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:127:3
    #1 0x10f5d57 in compress_chunk /home/iii/zlib-ng/arch-systemz/clang/asan-on/libfuzzer-off/dfltcc-deflate/test/switchlevels.c:105:5
    #2 0x10f5d57 in main /home/iii/zlib-ng/arch-systemz/clang/asan-on/libfuzzer-off/dfltcc-deflate/test/switchlevels.c:155:13

previously allocated by thread T0 here:
    #0 0x10befc3 in malloc /home/iii/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x10f5b15 in compress_chunk /home/iii/zlib-ng/arch-systemz/clang/asan-on/libfuzzer-off/dfltcc-deflate/test/switchlevels.c:76:11
    #2 0x10f5b15 in main /home/iii/zlib-ng/arch-systemz/clang/asan-on/libfuzzer-off/dfltcc-deflate/test/switchlevels.c:155:13

SUMMARY: AddressSanitizer: heap-use-after-free /home/iii/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:22:3 in __asan_memcpy
Shadow bytes around the buggy address:
  0x100c2dffffffc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100c2dffffffd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100c2dffffffe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100c2dfffffff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100c2e00000000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x100c2e00000010: fd fd fd[fd]fd fd fd fd fd fd fd fd fd fd fd fd
  0x100c2e00000020: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x100c2e00000030: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x100c2e00000040: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x100c2e00000050: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x100c2e00000060: fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==1731846==ABORTING
```

Before I start diving too deep into that, does someone maybe have an idea what could be causing this?

EDIT: Bisect points to my https://github.com/zlib-ng/zlib-ng/commit/40acb3fe1e79a3ca441ef38325a357e02fc96a6d, so I guess I'll have to investigate myself.

EDIT2: That's `switchlevels` deficiency: `deflateParams()` is called while `next_out` points to a stale buffer. I'll send a PR.

### PR DESCRIPTION
**Pull request by iii-i**
Fixes: #776

### CODE REVIEW

File: test/switchlevels.c [hunk 1]
```diff
@@ -82,11 +76,18 @@ static int compress_chunk(PREFIX3(stream) *strm, int level, int size, int last)
...
-    strm->next_in = buf;
-    strm->avail_in = size;
+    strm->next_in = NULL;
+    strm->avail_in = 0;
     strm->next_out = buf + size;
     strm->avail_out = compsize;
+    err = PREFIX(deflateParams)(strm, level, Z_DEFAULT_STRATEGY);
+    if (err != Z_OK) {
+        fprintf(stderr, "deflateParams() failed with code %d\n", err);
+        goto done;
```
Comment (iii-i) [inline test/switchlevels.c]: Should be `free_buf` now.

File: test/switchlevels.c [hunk 2]
```diff
@@ -82,11 +76,18 @@ static int compress_chunk(PREFIX3(stream) *strm, int level, int size, int last)
         goto free_buf;
     }
 
-    strm->next_in = buf;
-    strm->avail_in = size;
+    strm->next_in = NULL;
+    strm->avail_in = 0;
```
Comment (nmoinvaz) [inline test/switchlevels.c:82]: Why this change? Doesn't seem to be doing the same thing as before? Why is the buffer "stale"? It seems `read_all` should fill it..

Comment (iii-i) [reply test/switchlevels.c:82]: `buf` is freed at the end of this function. So when we enter it again, we hit UAF in case `deflateParams()` needs to write something.

However, if we only move the allocation, then `deflateParams()` will perform compression, leaving `deflate()` with nothing to do. Therefore: give `deflateParams()` empty input buffer and let it flush. And then give the real input buffer to `deflate()`.

Comment (nmoinvaz) [reply test/switchlevels.c:82]: I see.. What about considering moving `strm->next_out` and `strm->avail_out` below `strm->next_in` and `strm->avail_in` to make it easier to read?

Comment (iii-i) [reply test/switchlevels.c:82]: Hm, isn't this already the case? Or do you mean the following?

```
     strm->next_in = NULL;
     strm->avail_in = 0;
...
     strm->next_in = buf;
     strm->avail_in = size;
     strm->next_out = buf + size;
     strm->avail_out = compsize;
```

This won't work, because `deflateParams()` would run with empty input buffer (good), but stale output buffer.

**Comment by iii-i** [comment]
Fixed cleanup sequence, added comments.

File: test/switchlevels.c (hunk 2 above)
Comment (mtl1979) [reply test/switchlevels.c:82]: I think adding the comment made reviewing the code a lot easier... I've been around since early days of zlib-ng but I still haven't memorized what all functions do in detail...
